spring:
    # 数据库配置
    datasource:
        username: uat账号
        password: uat密码
        url: jdbc:mysql://uat地址/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.jdbc.Driver
    # 引擎模板配置
    thymeleaf:
        cache: false # 关闭缓存
        prefix: classpath:/views/ # 指定 thymeleaf 模板路径
        suffix: .html
        encoding: UTF-8 # 指定字符集编码

    # redis 配置
    redis:
        host: uat配置
        port: uat端口
        password: uat密码
        jedis:
            pool:
                max-idle: 8  # 连接池最大空闲连接
                min-idle: 0  # 连接池中的最小空闲连接
                max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
                max-wait: 10000ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        connect-timeout: 300 #连接超时时间（毫秒）


server:
    port: 12980